"""An image-generator plugin using the v1 ImageGenerator contract."""

from manga_director import ImageResult
from manga_director.plugins import PluginRegistry, PluginType


class SampleImageGenerator:
    def generate(self, prompt: str) -> ImageResult:
        return ImageResult(
            success=True,
            image_path="sample-plugin://page.png",
            metadata={"prompt_length": len(prompt)},
            provider="sample-image",
            elapsed_time=0.0,
            messages=["Generated by the sample plugin."],
        )


class SampleImagePlugin:
    name = "sample-image"
    version = "1.0.0"
    description = "Adds a deterministic sample image provider."

    def initialize(self) -> None:
        pass

    def register(self, registry: PluginRegistry) -> None:
        registry.register(
            PluginType.IMAGE_GENERATOR,
            "sample-image",
            SampleImageGenerator,
            plugin_name=self.name,
        )

    def shutdown(self) -> None:
        pass
