from typing import Protocol

from manga_director.domain.project import Project


class ProjectRepository(Protocol):
    def load(self, project_id: str) -> Project: ...

    def save(self, project: Project) -> None: ...

    def exists(self, project_id: str) -> bool: ...

    def delete(self, project_id: str) -> None: ...

    def list(self) -> list[Project]: ...
